name: fpm

on: [push, pull_request]

jobs:
  gfortran:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        gcc_v: [10] # Version of GFortran we want to use.
        include:
        - os: ubuntu-latest
          os-arch: linux-x86_64

        - os: windows-latest
          os-arch: windows-x86_64

        - os: macos-latest
          os-arch: macos-x86_64

    env:
      FC: gfortran
      GCC_V: ${{ matrix.gcc_v }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install GFortran Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${GCC_V}

    - name: Install GFortran Windows
      if: contains(matrix.os, 'windows')
      run: |
        Invoke-WebRequest -Uri https://dw.fortran.rocks/MinGW-12-2554e2d.7z -OutFile MinGW-12-2554e2d.7z
        7z x MinGW-12-2554e2d.7z
        echo "$pwd\MinGW-12-2554e2d\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install GFortran macOS
      if: contains(matrix.os, 'macos')
      run: |
        ln -s /usr/local/bin/gfortran-${GCC_V} /usr/local/bin/gfortran

    - name: Install fpm
      uses: fortran-lang/setup-fpm@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        gfortran --version
        fpm build

    - name: Search
      run: |
        fpm run
        fpm run -- FORTRAN
        fpm run -- PARSER
        fpm run -- hash
        fpm run -- pixel -V
        fpm run -- -V
